# Generated by Django 3.1.7 on 2024-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formas',
            name='siglas',
            field=models.CharField(default='R', max_length=5),
        ),
    ]
