# Generated by Django 3.1.7 on 2024-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qs', '0002_formas_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formas',
            name='siglas',
            field=models.CharField(max_length=5),
        ),
    ]
