# Generated by Django 3.1.7 on 2024-12-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
        ('qs', '0003_auto_20241220_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='acabado',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='calidad',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='montajes',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='norma',
        ),
        migrations.AlterField(
            model_name='variante',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo'),
        ),
        migrations.DeleteModel(
            name='Acabado',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Calidad',
        ),
        migrations.DeleteModel(
            name='Formas',
        ),
        migrations.DeleteModel(
            name='Norma',
        ),
    ]
