# Generated by Django 3.1.7 on 2025-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qs', '0005_auto_20250304_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='w_cab',
            field=models.FloatField(default=0),
        ),
    ]
