# Generated by Django 3.1.7 on 2025-03-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_articulo_dst'),
        ('qs', '0006_variante_w_cab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='articulos.articulo'),
        ),
    ]
