# Generated by Django 3.1.7 on 2023-03-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('conjuntos', models.ManyToManyField(related_name='grupos', to='rodillos.Conjunto')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('siglas', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='rodillos.operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Rodillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.material')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodillos', to='rodillos.posicion')),
            ],
        ),
        migrations.AddField(
            model_name='operacion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='rodillos.seccion'),
        ),
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('conjuntos', models.ManyToManyField(related_name='montajes', to='rodillos.Conjunto')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.grupo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montajes', to='estructura.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fichero', models.FileField(upload_to='ficheros')),
                ('rodillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheros', to='rodillos.rodillo')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='rodillos.conjunto')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.posicion')),
                ('rodillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.rodillo')),
            ],
        ),
        migrations.AddField(
            model_name='conjunto',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='rodillos.seccion'),
        ),
    ]
