# Generated by Django 3.1.7 on 2023-03-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='siglas',
        ),
    ]
