# Generated by Django 3.1.7 on 2023-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0002_remove_operacion_siglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='cantidad',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
