# Generated by Django 3.1.7 on 2023-03-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0004_remove_posicion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
