# Generated by Django 3.1.7 on 2023-06-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('rodillos', '0005_posicion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='maquina',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.zona'),
        ),
    ]
