# Generated by Django 3.1.7 on 2023-06-13 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('rodillos', '0006_grupo_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.zona'),
        ),
    ]
