# Generated by Django 3.1.7 on 2023-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0007_auto_20230613_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='tubo_madre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tubo_madre',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='seccion',
            name='pertenece_grupo',
            field=models.BooleanField(default=True),
        ),
    ]
