# Generated by Django 3.1.7 on 2023-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0009_auto_20230613_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='tubo_madre',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='tubo_madre',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
