# Generated by Django 4.0.4 on 2023-06-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0010_auto_20230613_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='tubo_madre',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
