# Generated by Django 3.1.7 on 2023-06-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('rodillos', '0010_auto_20230629_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bancada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.bancada')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='rodillos.operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='rodillos.operacion')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tubo_madre', models.FloatField()),
                ('bancadas', models.ManyToManyField(related_name='grupos', to='rodillos.Bancada')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_rodillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bancadas', models.ManyToManyField(related_name='montajes', to='rodillos.Bancada')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.grupo')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montajes', to='estructura.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='rodillos.conjunto')),
                ('eje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.eje')),
                ('rodillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.rodillo')),
            ],
        ),
        migrations.AddField(
            model_name='rodillo',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_rodillo'),
            preserve_default=False,
        ),
    ]
