# Generated by Django 3.1.7 on 2023-06-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0011_auto_20230629_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_rodillo'),
            preserve_default=False,
        ),
    ]
