# Generated by Django 4.0.4 on 2023-06-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0011_alter_conjunto_tubo_madre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjunto',
            name='tubo_madre',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
