# Generated by Django 3.1.7 on 2023-06-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0012_eje_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='bancadas',
        ),
        migrations.AddField(
            model_name='bancada',
            name='grupos',
            field=models.ManyToManyField(related_name='bancadas', to='rodillos.Grupo'),
        ),
        migrations.AddField(
            model_name='eje',
            name='diametro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.grupo'),
        ),
    ]
