# Generated by Django 3.1.7 on 2023-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0013_auto_20230629_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconos'),
        ),
    ]
