# Generated by Django 3.1.7 on 2023-06-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0014_auto_20230629_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rodillos', models.ManyToManyField(related_name='planos', to='rodillos.Rodillo')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=250)),
                ('archivo', models.FileField(upload_to='planos')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.plano')),
            ],
        ),
    ]
