# Generated by Django 3.1.7 on 2023-06-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0015_plano_revision'),
    ]

    operations = [
    ]
