# Generated by Django 3.1.7 on 2023-06-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0016_merge_20230630_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('planos', models.ManyToManyField(related_name='instancias', to='rodillos.Plano')),
                ('rodillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.rodillo')),
            ],
        ),
        migrations.CreateModel(
            name='Nombres_Parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros_Estandar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('rodillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.rodillo')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('croquis', models.ImageField(blank=True, null=True, upload_to='croquis')),
                ('nombres', models.ManyToManyField(related_name='tipo_plano', to='rodillos.Nombres_Parametros')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Ficheros',
        ),
        migrations.AddField(
            model_name='tipo_plano',
            name='tipo_seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_seccion'),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='tipo_plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_plano'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_seccion'),
        ),
    ]
