# Generated by Django 3.1.7 on 2023-06-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0010_auto_20230613_1732'),
        ('rodillos', '0017_auto_20230630_1914'),
    ]

    operations = [
    ]
