# Generated by Django 3.1.7 on 2023-06-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0018_merge_20230630_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='tubo_madre',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
