# Generated by Django 3.1.7 on 2023-09-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0019_revision_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_plano',
            name='tipo_rodillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_rodillo'),
        ),
    ]
