# Generated by Django 4.0.4 on 2023-07-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0019_auto_20230630_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='tubo_madre',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
