# Generated by Django 3.1.7 on 2023-09-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0020_tipo_plano_tipo_rodillo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_plano',
            old_name='Tipo_rodillo',
            new_name='tipo_rodillo',
        ),
    ]
