# Generated by Django 3.1.7 on 2023-09-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0020_tipo_plano_tipo_rodillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_plano',
            name='tipo_rodillo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_rodillo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipo_plano',
            name='tipo_seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rodillos.tipo_seccion'),
            preserve_default=False,
        ),
    ]
