# Generated by Django 3.1.7 on 2023-10-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0022_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bancada',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='eje',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='elemento',
            name='nombre',
        ),
    ]
