# Generated by Django 3.1.7 on 2023-11-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0025_auto_20231114_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjunto',
            name='bancada',
        ),
        migrations.RemoveField(
            model_name='conjunto',
            name='icono',
        ),
        migrations.AddField(
            model_name='bancada',
            name='dimensiones',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos')),
                ('bancada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.bancada')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.conjunto')),
            ],
        ),
    ]
