# Generated by Django 3.1.7 on 2023-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0026_auto_20231114_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='bancadas',
            field=models.ManyToManyField(blank=True, null=True, related_name='grupos', to='rodillos.Bancada'),
        ),
    ]
