# Generated by Django 3.1.7 on 2023-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0027_auto_20231123_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
