# Generated by Django 3.1.7 on 2024-01-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0028_auto_20231127_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='rodillo',
            name='descripcion_perfil',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='dimension_perfil',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='bancadas',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='rodillos.Bancada'),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='forma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.forma'),
        ),
    ]
