# Generated by Django 3.1.7 on 2024-02-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0029_auto_20240111_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montaje',
            name='bancadas',
        ),
        migrations.AddField(
            model_name='montaje',
            name='bancadas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.bancada'),
        ),
    ]
