# Generated by Django 3.1.7 on 2024-02-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0030_auto_20240212_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='anotciones_montaje',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
