# Generated by Django 3.1.7 on 2024-03-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0031_elemento_anotciones_montaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_rodillo',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
