# Generated by Django 3.1.7 on 2024-03-08 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0032_tipo_rodillo_siglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='celda',
            name='operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='rodillos.operacion'),
        ),
    ]
