# Generated by Django 3.1.7 on 2024-04-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0034_auto_20240403_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='cod_antiguo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
