# Generated by Django 3.1.7 on 2024-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0035_plano_cod_antiguo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='descripcion',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
