# Generated by Django 3.1.7 on 2024-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0036_plano_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
