# Generated by Django 3.1.7 on 2024-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0037_revision_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='eje',
            name='numero_ejes',
            field=models.IntegerField(default=1),
        ),
    ]
