# Generated by Django 3.1.7 on 2024-05-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0038_eje_numero_ejes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos')),
            ],
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='icono',
        ),
        migrations.AddField(
            model_name='operacion',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.icono'),
        ),
    ]
