# Generated by Django 3.1.7 on 2024-07-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0039_auto_20240503_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rodillo',
            name='material',
        ),
    ]
