# Generated by Django 3.1.7 on 2024-07-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0040_remove_rodillo_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='espesores',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='espesor_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grupo',
            name='espesor_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='espesor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='espesor_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='rodillo',
            name='espesor_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
