# Generated by Django 3.1.7 on 2024-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0041_auto_20240730_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancada',
            name='espesores',
            field=models.CharField(default='0÷0', max_length=10),
        ),
    ]
