# Generated by Django 3.1.7 on 2024-09-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0043_remove_instancia_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='diametro',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='especial',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.material'),
        ),
    ]
