# Generated by Django 3.1.7 on 2024-09-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0044_auto_20240924_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='contador',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
