# Generated by Django 3.1.7 on 2024-09-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0046_remove_revision_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='activa_qs',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='instancia',
            name='diametro_ext',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
