# Generated by Django 3.1.7 on 2024-10-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0047_auto_20240930_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='obsoleta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
