# Generated by Django 3.1.7 on 2024-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0048_instancia_obsoleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodillo',
            name='num_instancias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
