# Generated by Django 3.1.7 on 2024-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0051_auto_20241014_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='ancho',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
