# Generated by Django 3.1.7 on 2024-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0052_instancia_ancho'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodillo',
            name='num_ejes',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
