# Generated by Django 3.1.7 on 2024-10-24 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodillos', '0053_rodillo_num_ejes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaRectificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('diametro', models.FloatField(blank=True, null=True)),
                ('diametro_ext', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('nuevo_diametro', models.FloatField(blank=True, null=True)),
                ('nuevo_diametro_ext', models.FloatField(blank=True, null=True)),
                ('nuevo_ancho', models.FloatField(blank=True, null=True)),
                ('fecha_rectificado', models.DateField(blank=True, null=True)),
                ('tipo_rectificado', models.CharField(choices=[('estandar', 'Estándar'), ('axial', 'Axial')], default='estandar', max_length=10)),
                ('instancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rodillos.instancia')),
                ('rectificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.rectificacion')),
                ('rectificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
