# Generated by Django 3.1.7 on 2024-10-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0054_linearectificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectificacion',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
