# Generated by Django 3.1.7 on 2024-10-28 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0056_linearectificacion_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectificacion',
            name='fecha_estimada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
