# Generated by Django 3.1.7 on 2024-10-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0058_auto_20241029_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancada',
            name='espesores',
            field=models.CharField(default='0÷0', max_length=20),
        ),
        migrations.AlterField(
            model_name='conjunto',
            name='espesores',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
