# Generated by Django 3.1.7 on 2024-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0059_auto_20241031_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancia',
            name='archivo',
        ),
        migrations.AddField(
            model_name='rodillo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='programa'),
        ),
    ]
