# Generated by Django 3.1.7 on 2024-11-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0060_auto_20241105_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearectificacion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
