# Generated by Django 3.1.7 on 2024-11-18 13:06

from django.db import migrations, models
import rodillos.storages


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0061_linearectificacion_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearectificacion',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=rodillos.storages.OverwriteStorage(), upload_to='programa'),
        ),
    ]
