# Generated by Django 3.1.7 on 2024-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0063_linearectificacion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancia',
            name='dieametro_centro',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
