# Generated by Django 3.1.7 on 2024-11-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0064_instancia_dieametro_centro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancia',
            old_name='dieametro_centro',
            new_name='diametro_centro',
        ),
    ]
