# Generated by Django 3.1.7 on 2024-11-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0067_auto_20241127_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='xa_rectificado',
            field=models.BooleanField(default=False),
        ),
    ]
