# Generated by Django 3.1.7 on 2024-12-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0069_auto_20241203_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('siglas', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instancia',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rodillos.posicion'),
        ),
    ]
