# Generated by Django 3.1.7 on 2024-12-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0070_auto_20241203_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancada',
            name='nombre_grupo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
