# Generated by Django 3.1.7 on 2024-12-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0071_bancada_nombre_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celda',
            name='bancada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='rodillos.bancada'),
        ),
    ]
