# Generated by Django 3.1.7 on 2024-12-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0072_auto_20241218_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancia',
            name='rodillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='rodillos.rodillo'),
        ),
        migrations.AlterField(
            model_name='parametros_estandar',
            name='rodillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='rodillos.rodillo'),
        ),
    ]
