# Generated by Django 3.1.7 on 2024-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0073_auto_20241218_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodillo',
            name='rectificado_por_parejas',
            field=models.BooleanField(default=True),
        ),
    ]
