# Generated by Django 3.1.7 on 2025-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0074_rodillo_rectificado_por_parejas'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
