# Generated by Django 3.1.7 on 2025-02-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0074_rodillo_rectificado_por_parejas'),
    ]

    operations = [
        migrations.AddField(
            model_name='montaje',
            name='titular_grupo',
            field=models.BooleanField(default=False),
        ),
    ]
