# Generated by Django 3.1.7 on 2025-02-03 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0075_montaje_titular_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celda',
            name='icono',
        ),
    ]
