# Generated by Django 3.1.7 on 2025-02-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0076_remove_celda_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icono_celda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='iconos_celda')),
            ],
        ),
        migrations.AddField(
            model_name='celda',
            name='icono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.icono_celda'),
        ),
    ]
