# Generated by Django 3.1.7 on 2025-02-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0077_auto_20250203_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='icono_celda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rodillos.icono_celda'),
        ),
    ]
