# Generated by Django 3.1.7 on 2025-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0079_auto_20250210_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='icono_celda',
            name='pertenece_grupo',
            field=models.BooleanField(default=True),
        ),
    ]
