# Generated by Django 3.1.7 on 2025-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0080_icono_celda_pertenece_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='icono_celda',
            name='pertenece_ct',
            field=models.BooleanField(default=False),
        ),
    ]
