# Generated by Django 3.1.7 on 2025-02-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0075_operacion_color'),
        ('rodillos', '0081_icono_celda_pertenece_ct'),
    ]

    operations = [
    ]
