# Generated by Django 3.1.7 on 2025-02-20 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0082_merge_20250220_1134'),
        ('rodillos', '0082_merge_20250220_0833'),
    ]

    operations = [
    ]
