# Generated by Django 3.1.7 on 2025-02-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0083_merge_20250220_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='anotaciones_montaje')),
                ('montaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rodillos.montaje', related_name='anotaciones')),
            ],
        ),
    ]
