# Generated by Django 3.1.7 on 2025-02-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0084_anotaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodillo',
            name='es_generico',
            field=models.BooleanField(default=False),
        ),
    ]
