# Generated by Django 3.1.7 on 2025-03-31 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0116_stockminimo_cantidad_aconsejable'),
        ('rodillos', '0085_rodillo_es_generico'),
    ]

    operations = [
        migrations.AddField(
            model_name='rectificacion',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repuestos.proveedor'),
        ),
    ]
