# Generated by Django 3.1.7 on 2025-04-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0086_rectificacion_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linearectificacion',
            name='instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineasinstancias', to='rodillos.instancia'),
        ),
    ]
