# Generated by Django 3.1.7 on 2025-05-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0089_auto_20250522_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='celda',
            name='color_celda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
