# Generated by Django 3.1.7 on 2026-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0090_celda_color_celda'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestrezasRodillos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
