# Generated by Django 3.1.7 on 2026-08-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0091_destrezasrodillos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodillo',
            name='dimension_perfil',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
