# Generated by Django 3.1.7 on 2026-09-01 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rodillos', '0092_auto_20260826_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_rectificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_rectificado')),
                ('linea_rectificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rodillos.linearectificacion')),
                ('rectificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rodillos.rectificacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_rectificado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
