# Generated by Django 3.1.7 on 2026-09-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0093_doc_rectificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_rectificado',
            name='linea_rectificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rodillos.linearectificacion'),
        ),
    ]
