# Generated by Django 3.1.7 on 2026-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0094_auto_20260901_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc_rectificado',
            name='linea_rectificacion',
        ),
        migrations.AddField(
            model_name='doc_rectificado',
            name='linea_rectificacion',
            field=models.ManyToManyField(blank=True, related_name='documentos', to='rodillos.LineaRectificacion'),
        ),
    ]
