# Generated by Django 3.1.7 on 2021-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_nivelacceso_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelacceso',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
    ]
