# Generated by Django 3.1.7 on 2021-05-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_perfil_nivel_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nivel_acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.nivelacceso'),
        ),
    ]
