# Generated by Django 4.0.4 on 2022-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0043_remove_notificacion_para'),
        ('administracion', '0009_perfil_destrezas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='destrezas',
            field=models.ManyToManyField(blank=True, related_name='operarios', to='mantenimiento.especialidad'),
        ),
    ]
