# Generated by Django 4.0.4 on 2022-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('administracion', '0010_alter_perfil_destrezas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='empresa',
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ManyToManyField(to='estructura.empresa'),
        ),
    ]
