# Generated by Django 4.0.4 on 2022-09-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('administracion', '0011_remove_perfil_empresa_perfil_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='empresa',
        ),
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estructura.empresa'),
            preserve_default=False,
        ),
    ]
