# Generated by Django 3.1.7 on 2026-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0021_destrezasvelocidad'),
        ('administracion', '0012_remove_perfil_empresa_perfil_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='destrezas_velocidad',
            field=models.ManyToManyField(blank=True, related_name='operarios_velocidad', to='velocidad.DestrezasVelocidad'),
        ),
    ]
