# Generated by Django 3.1.7 on 2026-03-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0006_destrezasfoso'),
        ('administracion', '0013_perfil_destrezas_velocidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='destrezas_foso',
            field=models.ManyToManyField(blank=True, related_name='operarios_foso', to='foso.DestrezasFoso'),
        ),
    ]
