# Generated by Django 3.1.7 on 2026-08-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodillos', '0092_auto_20260826_1043'),
        ('administracion', '0014_perfil_destrezas_foso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='destrezas_rodillos',
            field=models.ManyToManyField(blank=True, related_name='operarios_rodillos', to='rodillos.DestrezasRodillos'),
        ),
    ]
