from django.contrib import admin
from .models import Tipo_Seccion, Seccion, Operacion, Eje, Rodillo, Tipo_rodillo, Material, Bancada, Conjunto, Elemento, Grupo, Montaje, Plano, Revision, Tipo_Plano, Nombres_Parametros, Instancia, Parametros_Estandar

admin.site.register(Tipo_Seccion)
admin.site.register(Seccion)
admin.site.register(Operacion)
admin.site.register(Eje)
admin.site.register(Rodillo)
admin.site.register(Tipo_rodillo)
admin.site.register(Material)
admin.site.register(Bancada)
admin.site.register(Conjunto)
admin.site.register(Elemento)
admin.site.register(Grupo)
admin.site.register(Montaje)
admin.site.register(Plano)
admin.site.register(Revision)
admin.site.register(Tipo_Plano)
admin.site.register(Nombres_Parametros)
admin.site.register(Instancia)
admin.site.register(Parametros_Estandar)