from django.contrib import admin
from .models import Entrega, LineaAdicional, ContadorPedidos, LineaSalida, Repuesto, Proveedor, Contacto, Pedido, LineaPedido, Movimiento, Almacen, Inventario, LineaInventario, Salida, StockMinimo, TipoRepuesto, TipoUnidad

admin.site.register(Repuesto)
admin.site.register(TipoUnidad)
admin.site.register(TipoRepuesto)
admin.site.register(Proveedor)
admin.site.register(Contacto)
admin.site.register(Pedido)
admin.site.register(LineaPedido)
admin.site.register(Movimiento)
admin.site.register(Almacen)
admin.site.register(Inventario)
admin.site.register(LineaInventario)
admin.site.register(StockMinimo)
admin.site.register(ContadorPedidos)
admin.site.register(LineaAdicional)
admin.site.register(Entrega)
admin.site.register(Salida)
admin.site.register(LineaSalida)