# Generated by Django 3.1.7 on 2021-11-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codpostal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='poblacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
