# Generated by Django 3.1.7 on 2021-11-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0003_auto_20211130_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='estructura.empresa'),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='poblacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
