# Generated by Django 3.1.7 on 2021-04-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_auto_20210405_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fabricante',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='equipos'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
