# Generated by Django 3.1.7 on 2021-11-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0004_auto_20211130_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codpostal',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='poblacion',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefono',
        ),
    ]
