# Generated by Django 3.1.7 on 2021-12-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_auto_20211130_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='direcciones',
            name='provincia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
