# Generated by Django 3.1.7 on 2021-04-06 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_auto_20210405_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='estructura.seccion'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='estructura.zona'),
        ),
        migrations.AlterField(
            model_name='zona',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='estructura.empresa'),
        ),
    ]
