# Generated by Django 3.1.7 on 2022-01-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_direcciones_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direcciones',
            name='codpostal',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='poblacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='direcciones',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
