# Generated by Django 3.1.7 on 2023-10-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='es_maquina_tubo',
            field=models.BooleanField(default=True),
        ),
    ]
