# Generated by Django 3.1.7 on 2021-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0008_auto_20210421_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
