# Generated by Django 3.1.7 on 2023-11-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0009_auto_20231107_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codpostal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
