# Generated by Django 3.1.7 on 2024-04-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0010_auto_20231115_1203'),
        ('estructura', '0008_zona_es_maquina_tubo'),
    ]

    operations = [
    ]
