# Generated by Django 3.1.7 on 2024-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0011_merge_20240430_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='espesor_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='zona',
            name='espesor_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
