# Generated by Django 3.1.7 on 2024-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0012_auto_20240823_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
