# Generated by Django 3.1.7 on 2024-12-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rodillos', '0074_rodillo_rectificado_por_parejas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acabado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('siglas', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dim1', models.CharField(max_length=5)),
                ('dim2', models.CharField(max_length=5)),
                ('espesor', models.CharField(max_length=4)),
                ('acabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.acabado')),
                ('calidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.calidad')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.formas')),
                ('montajes', models.ManyToManyField(related_name='articulos', to='rodillos.Montaje')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.norma')),
            ],
        ),
    ]
