# Generated by Django 3.1.7 on 2025-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulo_desarrollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='desarrollo',
            field=models.IntegerField(),
        ),
    ]
