# Generated by Django 3.1.7 on 2025-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20250104_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='Dst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
