# Generated by Django 3.1.7 on 2021-06-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.empresa')),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='completo',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repuestos.almacen'),
        ),
    ]
