# Generated by Django 3.1.7 on 2021-04-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0006_auto_20210405_2213'),
        ('repuestos', '0002_auto_20210406_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='estructura.equipo'),
        ),
    ]
