# Generated by Django 3.1.7 on 2021-04-06 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0004_auto_20210406_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='repuestos.proveedor'),
        ),
    ]
