# Generated by Django 3.1.7 on 2021-04-06 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0005_auto_20210406_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='es_critico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(default=datetime.date(2021, 4, 6))),
                ('fecha_entrega', models.DateField(blank=True)),
                ('completo', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date(2021, 4, 6))),
                ('cantidad', models.IntegerField()),
                ('linea_pedido', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='repuestos.lineapedido')),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.pedido'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('preveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.proveedor')),
            ],
        ),
    ]
