# Generated by Django 3.1.7 on 2021-06-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0005_lineainventario_repuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineainventario',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto'),
        ),
    ]
