# Generated by Django 3.1.7 on 2021-06-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0006_auto_20210624_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineainventario',
            name='cantidad',
        ),
    ]
