# Generated by Django 3.1.7 on 2021-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0007_remove_lineainventario_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(default='Ajuste inicial', max_length=100),
        ),
        migrations.AddField(
            model_name='lineainventario',
            name='observaciones',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
