# Generated by Django 3.1.7 on 2021-06-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0008_auto_20210625_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineainventario',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='lineainventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repuestos.almacen'),
        ),
        migrations.AddField(
            model_name='lineainventario',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
