# Generated by Django 3.1.7 on 2021-06-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0009_auto_20210625_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineainventario',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.almacen'),
        ),
    ]
