# Generated by Django 3.1.7 on 2021-06-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
        ('repuestos', '0010_auto_20210625_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='equipos',
            field=models.ManyToManyField(related_name='repuestos', to='estructura.Equipo'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='proveedores',
            field=models.ManyToManyField(related_name='repuestos', to='repuestos.Proveedor'),
        ),
    ]
