# Generated by Django 3.1.7 on 2021-06-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0011_auto_20210625_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='stock_minimo',
        ),
        migrations.CreateModel(
            name='StockMinimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.almacen')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto')),
            ],
        ),
    ]
