# Generated by Django 3.1.7 on 2021-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20210406_2024'),
        ('repuestos', '0011_auto_20210406_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='repuesto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='repuesto',
            name='equipos',
            field=models.ManyToManyField(to='estructura.Equipo'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='proveedores',
            field=models.ManyToManyField(to='repuestos.Proveedor'),
        ),
    ]
