# Generated by Django 3.1.7 on 2021-08-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0014_auto_20210628_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='descatalogado',
            field=models.BooleanField(default=False),
        ),
    ]
