# Generated by Django 3.1.7 on 2021-10-06 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repuestos', '0018_auto_20210924_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='repuestos.proveedor'),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='repuestos.pedido'),
        ),
        migrations.CreateModel(
            name='LineaAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_adicionales', to='repuestos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('linea_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.lineaadicional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
