# Generated by Django 3.1.7 on 2021-10-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0019_auto_20211006_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorPedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
    ]
