# Generated by Django 3.1.7 on 2021-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0022_movimiento_albaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
