# Generated by Django 3.1.7 on 2021-10-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0023_pedido_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
