# Generated by Django 3.1.7 on 2021-10-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0001_initial'),
        ('repuestos', '0025_auto_20211011_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorpedidos',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.empresa'),
        ),
    ]
