# Generated by Django 3.1.7 on 2021-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0027_pedido_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockminimo',
            name='localizacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
