# Generated by Django 3.1.7 on 2021-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0029_stockminimo_stock_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='por_recibir',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockminimo',
            name='stock_pendiente',
            field=models.IntegerField(default=0),
        ),
    ]
