# Generated by Django 3.1.7 on 2021-10-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0030_auto_20211026_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockminimo',
            name='stock_pendiente',
        ),
    ]
