# Generated by Django 3.1.7 on 2021-11-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0031_remove_stockminimo_stock_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaadicional',
            name='por_recibir',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
