# Generated by Django 3.1.7 on 2021-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0033_auto_20211105_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockminimo',
            name='stock_act',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
