# Generated by Django 3.1.7 on 2021-11-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0034_stockminimo_stock_act'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockminimo',
            name='stock_act',
        ),
    ]
