# Generated by Django 3.1.7 on 2021-11-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0036_stockminimo_stock_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockminimo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockminimo',
            name='stock_act',
            field=models.IntegerField(default=0),
        ),
    ]
