# Generated by Django 3.1.7 on 2021-11-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0037_auto_20211112_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaadicional',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='descuento',
            field=models.FloatField(default=0),
        ),
    ]
