# Generated by Django 3.1.7 on 2021-11-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0005_auto_20211130_1707'),
        ('repuestos', '0038_auto_20211130_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='contacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repuestos.contacto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estructura.direcciones'),
        ),
    ]
