# Generated by Django 3.1.7 on 2021-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0040_auto_20211130_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(blank=0, decimal_places=2, default=0, max_digits=8, null=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_prevista_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='descuento',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=4, null=0),
        ),
    ]
