# Generated by Django 3.1.7 on 2021-12-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0041_auto_20211202_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
