# Generated by Django 3.1.7 on 2021-12-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0043_auto_20211202_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaadicional',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
