# Generated by Django 3.1.7 on 2021-12-21 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0045_auto_20211217_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineasalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='repuestos.salida'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 12, 21)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2021, 12, 21)),
        ),
    ]
