# Generated by Django 3.1.7 on 2021-12-21 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0047_auto_20211221_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_creacion',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
