# Generated by Django 3.1.7 on 2021-12-21 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0048_auto_20211221_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
