# Generated by Django 3.1.7 on 2022-01-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0049_auto_20211221_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
