# Generated by Django 3.1.7 on 2022-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0051_pedido_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='stock_resultante',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
