# Generated by Django 3.1.7 on 2022-02-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0052_movimiento_stock_resultante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='stock_resultante',
        ),
    ]
