# Generated by Django 3.1.7 on 2022-02-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0054_auto_20220207_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineasalida',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.almacen'),
        ),
        migrations.AlterField(
            model_name='lineasalida',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto'),
        ),
        migrations.AlterField(
            model_name='lineasalida',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='repuestos.salida'),
        ),
    ]
