# Generated by Django 3.1.7 on 2022-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0055_auto_20220208_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='nombre_comun',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
