# Generated by Django 3.1.7 on 2022-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0056_repuesto_nombre_comun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombre_comun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
