# Generated by Django 3.1.7 on 2022-02-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0058_tipounidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='tipo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='repuestos.tipounidad'),
        ),
    ]
