# Generated by Django 3.1.7 on 2022-02-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0059_repuesto_tipo_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidad',
            name='siglas',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
