# Generated by Django 3.1.7 on 2022-02-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0060_tipounidad_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='tipo_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='repuestos.tipounidad'),
        ),
    ]
