# Generated by Django 3.1.7 on 2022-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('repuestos', '0060_tipounidad_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='equipos',
            field=models.ManyToManyField(null=True, related_name='repuestos', to='estructura.Equipo'),
        ),
    ]
