# Generated by Django 4.0.4 on 2022-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0061_auto_20220221_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='modelo',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
