# Generated by Django 3.1.7 on 2022-06-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0061_auto_20220221_1250'),
        ('repuestos', '0062_auto_20220218_1008'),
    ]

    operations = [
    ]
