# Generated by Django 4.0.4 on 2022-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0062_alter_lineaadicional_precio_alter_lineapedido_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observaciones2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
