# Generated by Django 4.0.4 on 2022-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0063_pedido_observaciones2'),
    ]

    operations = [
        
    ]
