# Generated by Django 3.1.7 on 2022-06-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('repuestos', '0063_merge_20220603_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='equipos',
            field=models.ManyToManyField(related_name='repuestos', to='estructura.Equipo'),
        ),
    ]
