# Generated by Django 4.0.4 on 2022-06-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0064_alter_lineaadicional_precio_and_more'),
    ]

    operations = [
        
    ]
