# Generated by Django 4.0.4 on 2022-06-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0065_alter_lineaadicional_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaadicional',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
