# Generated by Django 3.1.7 on 2022-06-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0066_alter_lineaadicional_descuento_and_more'),
        ('repuestos', '0064_auto_20220603_1111'),
    ]

    operations = [
    ]
