# Generated by Django 4.0.4 on 2022-07-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0067_merge_20220603_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
