# Generated by Django 4.0.4 on 2022-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0068_alter_repuesto_nombre'),
    ]

    operations = [
    ]
