# Generated by Django 4.0.4 on 2022-10-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0069_alter_lineapedido_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
