# Generated by Django 4.0.4 on 2022-10-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0071_alter_lineapedido_precio_alter_lineapedido_total'),
    ]

    operations = [
    ]
