# Generated by Django 4.0.4 on 2022-11-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0074_remove_preciounidad_repuesto_repuesto_precios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='precios',
        ),
        migrations.AddField(
            model_name='preciounidad',
            name='repuesto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='repuestos.repuesto'),
            preserve_default=False,
        ),
    ]
