# Generated by Django 4.0.4 on 2022-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0075_remove_repuesto_precios_preciounidad_repuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciounidad',
            name='proveedor',
            field=models.ManyToManyField(blank=True, null=True, to='repuestos.proveedor'),
        ),
    ]
