# Generated by Django 4.0.4 on 2022-11-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0076_alter_preciounidad_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preciounidad',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='preciounidad',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repuestos.proveedor'),
        ),
    ]
