# Generated by Django 4.0.4 on 2022-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0077_remove_preciounidad_proveedor_preciounidad_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
