# Generated by Django 4.0.4 on 2022-11-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0078_alter_lineapedido_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrecioUnidad',
            new_name='PrecioRepuesto',
        ),
    ]
