# Generated by Django 4.0.4 on 2022-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0080_alter_repuesto_proveedores'),
    ]

    operations = [
    ]
