# Generated by Django 4.0.4 on 2022-11-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0080_alter_repuesto_proveedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
