# Generated by Django 4.0.4 on 2022-11-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0083_alter_lineaadicional_precio_alter_lineapedido_precio_and_more'),
    ]

    operations = [
       
    ]
