# Generated by Django 4.0.4 on 2022-11-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0084_alter_lineaadicional_precio_alter_lineapedido_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaadicional',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='por_recibir',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
