# Generated by Django 4.0.4 on 2022-11-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0086_preciorepuesto_descuento'),
    ]

    operations = [
       
    ]
