# Generated by Django 4.0.4 on 2022-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0087_alter_lineapedido_precio_alter_lineapedido_total'),
    ]

    operations = [
    ]
