# Generated by Django 4.0.4 on 2022-12-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0088_alter_lineaadicional_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
