# Generated by Django 4.0.4 on 2023-01-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0090_alter_lineaadicional_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineaadicional',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='preciorepuesto',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='preciorepuesto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True),
        ),
    ]
