# Generated by Django 4.0.4 on 2023-01-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0091_alter_lineaadicional_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
