# Generated by Django 4.0.4 on 2023-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0092_alter_repuesto_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciorepuesto',
            name='descripcion_proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
