# Generated by Django 4.0.4 on 2023-03-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0093_preciorepuesto_descripcion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='descripcion_proveedor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
