# Generated by Django 4.0.4 on 2023-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0094_lineapedido_descripcion_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciorepuesto',
            name='modelo_proveedor',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
