# Generated by Django 4.0.4 on 2023-05-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0096_lineapedido_modelo_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciorepuesto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repuestos.proveedor'),
        ),
    ]
