# Generated by Django 4.0.4 on 2023-05-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0097_alter_preciorepuesto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciorepuesto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preciorepuesto',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='repuestos.repuesto'),
        ),
    ]
