# Generated by Django 3.1.7 on 2023-11-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0098_preciorepuesto_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='condicion_entrega',
            field=models.CharField(default='DAP ES-IBI', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(default='PAGARÉ A 45 DÍAS, DÍAS DE PAGO 10 Y 25', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='iva',
            field=models.IntegerField(default=21),
        ),
    ]
