# Generated by Django 3.1.7 on 2023-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0101_auto_20231107_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cif',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
