# Generated by Django 3.1.7 on 2023-11-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0102_proveedor_cif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='iva',
        ),
    ]
