# Generated by Django 3.1.7 on 2023-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0104_proveedor_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cod_ekon',
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
