# Generated by Django 3.1.7 on 2023-11-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0105_auto_20231115_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(default='FORMA HABITUAL', max_length=50),
        ),
    ]
