# Generated by Django 3.1.7 on 2024-01-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0108_auto_20231205_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cif',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
