# Generated by Django 3.1.7 on 2024-11-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0111_auto_20241115_1433'),
        ('repuestos', '0111_auto_20240829_0927'),
    ]

    operations = [
    ]
