# Generated by Django 3.1.7 on 2024-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0112_merge_20241118_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='de_rectificado',
            field=models.BooleanField(default=False),
        ),
    ]
