# Generated by Django 3.1.7 on 2025-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0113_proveedor_de_rectificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
