# Generated by Django 3.1.7 on 2025-03-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0115_auto_20250224_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockminimo',
            name='cantidad_aconsejable',
            field=models.IntegerField(default=0),
        ),
    ]
