# Generated by Django 3.1.7 on 2025-04-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0061_notificacion_seguridad'),
        ('repuestos', '0116_stockminimo_cantidad_aconsejable'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='num_parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.partetrabajo'),
        ),
    ]
