# Generated by Django 3.1.7 on 2025-04-10 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0117_salida_num_parte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_repuesto', to='repuestos.repuesto'),
        ),
    ]
