# Generated by Django 3.1.7 on 2025-05-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('repuestos', '0118_auto_20250410_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='equipos',
            field=models.ManyToManyField(blank=True, related_name='repuestos', to='estructura.Equipo'),
        ),
    ]
