# Generated by Django 3.1.7 on 2025-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0118_auto_20250410_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='lineaadicional',
            name='por_recibir',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='lineainventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='por_recibir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='lineasalida',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockminimo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockminimo',
            name='cantidad_aconsejable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockminimo',
            name='stock_act',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13),
        ),
    ]
