# Generated by Django 3.1.7 on 2025-04-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0119_auto_20250414_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='tipo_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='repuestos.tipounidad'),
        ),
    ]
