# Generated by Django 3.1.7 on 2025-06-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0120_lineapedido_tipo_unidad'),
        ('repuestos', '0119_auto_20250519_1756'),
    ]

    operations = [
    ]
