# Generated by Django 3.1.7 on 2025-06-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0120_lineapedido_tipo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='linea_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='repuestos.lineapedido'),
        ),
    ]
