# Generated by Django 3.1.7 on 2025-06-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0121_auto_20250619_1024'),
        ('repuestos', '0121_merge_20250612_1137'),
    ]

    operations = [
    ]
