# Generated by Django 3.1.7 on 2025-06-25 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0122_merge_20250625_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='linea_adicional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='repuestos.lineaadicional'),
        ),
    ]
