# Generated by Django 3.1.7 on 2025-06-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0123_auto_20250625_1041'),
        ('repuestos', '0122_merge_20250623_1724'),
    ]

    operations = [
    ]
