# Generated by Django 3.1.7 on 2025-07-07 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0061_notificacion_seguridad'),
        ('repuestos', '0124_merge_20250625_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='num_linea_tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.lineapartetrabajo'),
        ),
    ]
