# Generated by Django 3.1.7 on 2025-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0125_salida_num_linea_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineasalida',
            name='consumido_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
