# Generated by Django 3.1.7 on 2025-11-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0126_lineasalida_consumido_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineasalida',
            name='precio_ultima_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
