# Generated by Django 3.1.7 on 2025-11-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0127_lineasalida_precio_ultima_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineasalida',
            name='descuento_ultima_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
