# Generated by Django 3.1.7 on 2025-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0128_lineasalida_descuento_ultima_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
