# Generated by Django 3.1.7 on 2025-11-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0129_auto_20251120_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observaciones',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observaciones2',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
