# Generated by Django 3.1.7 on 2026-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0130_auto_20251125_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_prevista_modificada',
            field=models.BooleanField(default=False),
        ),
    ]
