# Generated by Django 3.1.7 on 2021-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
