# Generated by Django 3.1.7 on 2025-10-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0002_zonaperfilvelocidad_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='frecuencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='potencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='presion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='nwords',
            field=models.IntegerField(default=4),
        ),
    ]
