# Generated by Django 3.1.7 on 2025-10-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0003_auto_20251030_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='frecuencia',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='potencia',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='presion',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='velocidad',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
