# Generated by Django 3.1.7 on 2025-10-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0004_auto_20251030_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='fuerza_max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='hf_fmax',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='hf_fmin',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='hf_pmax',
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='v_max',
            field=models.IntegerField(default=100),
        ),
    ]
