# Generated by Django 3.1.7 on 2025-11-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('velocidad', '0005_auto_20251031_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='velocidad.codigoparada')),
            ],
        ),
        migrations.CreateModel(
            name='TipoParada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='control_paradas',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Perido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(null=True)),
                ('fin', models.DateTimeField(null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='velocidad.parada')),
            ],
        ),
        migrations.AddField(
            model_name='codigoparada',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='velocidad.tipoparada'),
        ),
        migrations.AddField(
            model_name='codigoparada',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_parada', to='estructura.zona'),
        ),
    ]
