# Generated by Django 3.1.7 on 2025-11-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0006_auto_20251121_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparada',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
