# Generated by Django 3.1.7 on 2025-11-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0007_tipoparada_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perido',
            new_name='Periodo',
        ),
    ]
