# Generated by Django 3.1.7 on 2025-11-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0008_auto_20251121_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='velocidad',
            field=models.FloatField(default=0),
        ),
    ]
