# Generated by Django 3.1.7 on 2025-11-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('velocidad', '0009_periodo_velocidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='zona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='estructura.zona'),
        ),
        migrations.AlterField(
            model_name='codigoparada',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_parada', to='estructura.zona'),
        ),
    ]
