# Generated by Django 3.1.7 on 2025-11-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('velocidad', '0010_auto_20251125_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='estructura.zona'),
        ),
    ]
