# Generated by Django 3.1.7 on 2025-11-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0011_auto_20251125_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoparada',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
