# Generated by Django 3.1.7 on 2025-12-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0012_codigoparada_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('inicio', models.TimeField(default='06:00')),
                ('fin', models.TimeField(default='22:00')),
                ('es_fin_de_semana', models.BooleanField(default=False)),
            ],
        ),
    ]
