# Generated by Django 3.1.7 on 2025-12-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0013_horariodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodia',
            name='nombre_dia',
            field=models.CharField(default='', max_length=20),
        ),
    ]
