# Generated by Django 3.1.7 on 2025-12-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('velocidad', '0014_horariodia_nombre_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodia',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='estructura.zona'),
        ),
        migrations.AlterField(
            model_name='horariodia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='horariodia',
            unique_together={('fecha', 'zona')},
        ),
    ]
