# Generated by Django 3.1.7 on 2025-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0015_auto_20251211_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariodia',
            old_name='es_fin_de_semana',
            new_name='es_festivo',
        ),
    ]
