# Generated by Django 3.1.7 on 2025-12-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0016_auto_20251212_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparada',
            name='para_informar',
            field=models.BooleanField(default=True),
        ),
    ]
