# Generated by Django 3.1.7 on 2026-01-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0017_tipoparada_para_informar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoparada',
            name='para_informar',
            field=models.BooleanField(default=False),
        ),
    ]
