# Generated by Django 3.1.7 on 2026-01-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0065_auto_20251120_0857'),
        ('velocidad', '0018_auto_20260108_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='parada',
            name='num_parte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.partetrabajo'),
        ),
        migrations.AddField(
            model_name='parada',
            name='observaciones',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
