# Generated by Django 3.1.7 on 2026-01-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0019_auto_20260114_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='num_parte',
        ),
    ]
