# Generated by Django 3.1.7 on 2026-01-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0020_remove_parada_num_parte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestrezasVelocidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
