# Generated by Django 3.1.7 on 2026-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0021_destrezasvelocidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='destrezasvelocidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
