# Generated by Django 3.1.7 on 2026-02-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('velocidad', '0022_destrezasvelocidad_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabrasClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.zona')),
            ],
        ),
        migrations.AddField(
            model_name='codigoparada',
            name='palabra_clave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='velocidad.palabrasclave'),
        ),
    ]
