# Generated by Django 3.1.7 on 2026-02-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0023_auto_20260203_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoparada',
            name='palabra_clave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='velocidad.palabrasclave'),
        ),
    ]
