# Generated by Django 3.1.7 on 2026-02-09 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estructura', '0013_auto_20241203_0710'),
        ('velocidad', '0024_auto_20260203_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodia',
            name='cambio_turno_1',
            field=models.TimeField(default='14:00'),
        ),
        migrations.AddField(
            model_name='horariodia',
            name='cambio_turno_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('maquinista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='estructura.zona')),
            ],
        ),
        migrations.AddField(
            model_name='horariodia',
            name='turno_mañana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_mañana', to='velocidad.turnos'),
        ),
        migrations.AddField(
            model_name='horariodia',
            name='turno_noche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_noche', to='velocidad.turnos'),
        ),
        migrations.AddField(
            model_name='horariodia',
            name='turno_tarde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario_tarde', to='velocidad.turnos'),
        ),
    ]
