# Generated by Django 3.1.7 on 2026-02-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0025_auto_20260209_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='velocidad.turnos'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='turno',
            field=models.CharField(max_length=1),
        ),
    ]
