# Generated by Django 3.1.7 on 2026-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0026_auto_20260211_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigoparada',
            name='codigoProdDB',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parada',
            name='of',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='parada',
            name='pos',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
