# Generated by Django 3.1.7 on 2026-02-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0027_auto_20260218_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoparada',
            name='codigoProdDB',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
