# Generated by Django 3.1.7 on 2026-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0028_auto_20260218_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoparada',
            name='siglas',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
