# Generated by Django 3.1.7 on 2026-02-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0029_tipoparada_siglas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parada',
            name='pos',
        ),
        migrations.CreateModel(
            name='ParadaProduccionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(blank=True, max_length=3, null=True)),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_prod_db', to='velocidad.parada')),
            ],
        ),
    ]
