# Generated by Django 3.1.7 on 2026-03-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0030_auto_20260225_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonaperfilvelocidad',
            old_name='control_paradas',
            new_name='lectura_hf',
        ),
        migrations.AddField(
            model_name='periodo',
            name='vmax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='vmax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='lectura_presion_soldadura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='lectura_vmax_sierra',
            field=models.BooleanField(default=False),
        ),
    ]
