# Generated by Django 3.1.7 on 2026-03-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0031_auto_20260309_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradaproducciondb',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='velocidad.turnos'),
        ),
    ]
