# Generated by Django 3.1.7 on 2026-03-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0032_paradaproducciondb_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradaproducciondb',
            name='orden_of',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
