# Generated by Django 3.1.7 on 2026-05-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocidad', '0033_paradaproducciondb_orden_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='tiempo_cambio_general',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='zonaperfilvelocidad',
            name='tiempo_cambio_parcial',
            field=models.IntegerField(default=60),
        ),
    ]
