# Generated by Django 3.1.7 on 2021-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='contacto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='observaciones',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
