# Generated by Django 3.1.7 on 2021-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0004_bascula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bascula',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
