# Generated by Django 3.1.7 on 2024-02-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0005_auto_20210523_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='puerta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
