# Generated by Django 3.1.7 on 2024-03-01 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0006_carga_puerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('puerta', models.IntegerField()),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargas.carga')),
            ],
        ),
    ]
