# Generated by Django 3.1.7 on 2024-03-01 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0007_llamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
