# Generated by Django 3.1.7 on 2024-03-01 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0008_auto_20240301_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
