# Generated by Django 3.1.7 on 2024-03-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0009_auto_20240301_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamada',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
