# Generated by Django 3.1.7 on 2024-03-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0010_auto_20240301_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='carga',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
