# Generated by Django 3.1.7 on 2025-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargas', '0011_carga_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
