# Generated by Django 3.1.7 on 2026-03-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bobina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('colada', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bobina',
                'verbose_name_plural': 'Bobinas',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.PositiveSmallIntegerField()),
                ('columna', models.PositiveSmallIntegerField()),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='foso.linea')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'ordering': ['linea', 'altura', 'columna'],
                'unique_together': {('linea', 'altura', 'columna')},
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('bobina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocupaciones', to='foso.bobina')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocupaciones', to='foso.posicion')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
