# Generated by Django 3.1.7 on 2026-03-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0002_auto_20260323_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobina',
            name='espesor_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
