# Generated by Django 3.1.7 on 2026-03-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0003_bobina_espesor_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bobina',
            name='diametro_mm',
        ),
        migrations.AddField(
            model_name='bobina',
            name='ref_proveedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
