# Generated by Django 3.1.7 on 2026-03-25 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0004_auto_20260325_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bobina',
            name='fecha_entrada',
            field=models.DateField(auto_now_add=True, default=datetime.date(2026, 3, 25)),
            preserve_default=False,
        ),
    ]
