# Generated by Django 3.1.7 on 2026-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0005_auto_20260325_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestrezasFoso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Destreza',
                'verbose_name_plural': 'Destrezas',
            },
        ),
    ]
