# Generated by Django 3.1.7 on 2026-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0006_destrezasfoso'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='motivo_anulacion',
            field=models.CharField(blank=True, help_text='Motivo por el que la posición no se puede usar', max_length=200, null=True),
        ),
    ]
