# Generated by Django 3.1.7 on 2026-04-09 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('foso', '0007_auto_20260408_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['foso', 'nombre'], 'verbose_name': 'Línea', 'verbose_name_plural': 'Líneas'},
        ),
        migrations.CreateModel(
            name='Foso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('columnas_por_altura', models.JSONField(default=dict, help_text='Ej: {"1": 9, "2": 8, "3": 9, "4": 8, "5": 9}')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fosos', to='estructura.empresa')),
            ],
            options={
                'verbose_name': 'Foso',
                'verbose_name_plural': 'Fosos',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='linea',
            name='foso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='foso.foso'),
            preserve_default=False,
        ),
    ]
