# Generated by Django 3.1.7 on 2026-04-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foso', '0008_auto_20260409_0843'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posicion',
            constraint=models.UniqueConstraint(fields=('linea', 'altura', 'columna'), name='uniq_posicion_por_linea_altura_columna'),
        ),
    ]
