# Generated by Django 3.1.7 on 2021-10-06 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_auto_20211006_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapartetrabajo',
            name='parte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='mantenimiento.partetrabajo'),
        ),
    ]
