# Generated by Django 3.1.7 on 2021-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_auto_20211018_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='numero',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
