# Generated by Django 3.1.7 on 2022-02-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_auto_20211020_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapartetrabajo',
            name='responsables',
        ),
        migrations.RemoveField(
            model_name='partetrabajo',
            name='notificacion',
        ),
        migrations.RemoveField(
            model_name='partetrabajo',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoperiodo'),
        ),
    ]
