# Generated by Django 3.1.7 on 2022-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_auto_20220228_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
