# Generated by Django 3.1.7 on 2022-03-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0010_auto_20220302_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='equipo',
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='equipo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='estructura.equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
