# Generated by Django 3.1.7 on 2022-03-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0011_auto_20220303_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.equipo'),
        ),
    ]
