# Generated by Django 3.1.7 on 2022-03-07 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0012_auto_20220303_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partetrabajo',
            name='tareas',
        ),
        migrations.AlterField(
            model_name='partetrabajo',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='pendiente',
            field=models.BooleanField(),
        ),
    ]
