# Generated by Django 3.1.7 on 2022-03-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0013_auto_20220307_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partes_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
