# Generated by Django 3.1.7 on 2022-03-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0015_auto_20220307_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='pendiente',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tipo_periodo',
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='periodo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='tipo_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoperiodo'),
        ),
    ]
