# Generated by Django 3.1.7 on 2022-03-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0016_auto_20220309_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='fecha_prevista_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
