# Generated by Django 3.1.7 on 2022-03-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0017_partetrabajo_fecha_prevista_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.seccion'),
        ),
        migrations.AddField(
            model_name='partetrabajo',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.zona'),
        ),
    ]
