# Generated by Django 3.1.7 on 2022-03-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0018_auto_20220309_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.empresa'),
        ),
    ]
