# Generated by Django 3.1.7 on 2022-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0020_auto_20220309_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='periodo',
            field=models.IntegerField(default=0),
        ),
    ]
