# Generated by Django 3.1.7 on 2022-03-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0026_auto_20220310_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
