# Generated by Django 3.1.7 on 2022-03-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0028_auto_20220314_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='tarea',
            field=models.ManyToManyField(blank=True, related_name='partes', to='mantenimiento.Tarea'),
        ),
    ]
