# Generated by Django 3.1.7 on 2022-03-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0029_auto_20220317_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapartetrabajo',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
