# Generated by Django 3.1.7 on 2022-03-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0030_lineapartetrabajo_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapartetrabajo',
            name='fecha_plan',
            field=models.DateField(blank=True, null=True),
        ),
    ]
