# Generated by Django 3.1.7 on 2022-03-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0031_lineapartetrabajo_fecha_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLineasTareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
    ]
