# Generated by Django 3.1.7 on 2022-03-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0033_auto_20220321_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.estadolineastareas'),
        ),
    ]
