# Generated by Django 4.0.4 on 2022-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0035_trabajadoreslineaparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='trabajo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
