# Generated by Django 4.0.4 on 2022-05-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0036_tarea_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='num_parte',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='ContadorPartes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('contador_parte', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.empresa')),
            ],
        ),
    ]
