# Generated by Django 4.0.4 on 2022-05-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0037_partetrabajo_num_parte_contadorpartes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='quien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
