# Generated by Django 4.0.4 on 2022-05-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0043_remove_notificacion_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='periodo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tipoperiodo'),
        ),
    ]
