# Generated by Django 4.0.4 on 2022-05-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0044_tarea_periodo_tarea_tipo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='seccion',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.seccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partetrabajo',
            name='zona',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.zona'),
            preserve_default=False,
        ),
    ]
