# Generated by Django 4.0.4 on 2022-05-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0047_alter_partetrabajo_seccion_alter_partetrabajo_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='zona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.zona'),
        ),
    ]
