# Generated by Django 4.0.4 on 2022-05-25 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0048_alter_partetrabajo_zona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partetrabajo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='partetrabajo',
            name='tipo_periodo',
        ),
    ]
