# Generated by Django 4.0.4 on 2022-05-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0050_remove_tarea_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.empresa'),
            preserve_default=False,
        ),
    ]
