# Generated by Django 4.0.4 on 2022-05-26 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0007_auto_20220117_1420'),
        ('mantenimiento', '0051_alter_partetrabajo_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partetrabajo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes_creados', to='estructura.empresa'),
        ),
    ]
