# Generated by Django 3.1.7 on 2022-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0052_alter_partetrabajo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoperiodo',
            name='cantidad_dias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
