# Generated by Django 3.1.7 on 2022-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0053_tipoperiodo_cantidad_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoperiodo',
            name='cantidad_dias',
            field=models.IntegerField(default=1),
        ),
    ]
