# Generated by Django 4.0.4 on 2022-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0053_tipoperiodo_cantidad_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observaciones_trab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
