# Generated by Django 4.0.4 on 2023-01-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0054_auto_20220704_1253'),
        ('mantenimiento', '0054_tarea_observaciones_trab'),
    ]

    operations = [
    ]
