# Generated by Django 4.0.4 on 2023-05-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0057_reclamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='conclusion',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
