# Generated by Django 4.0.4 on 2023-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0059_notificacion_peligrosidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapartetrabajo',
            name='observaciones_trab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
