# Generated by Django 3.1.7 on 2024-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0060_lineapartetrabajo_observaciones_trab'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='seguridad',
            field=models.BooleanField(default=False),
        ),
    ]
