# Generated by Django 3.1.7 on 2025-10-23 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mantenimiento', '0061_notificacion_seguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='mantenimiento.lineapartetrabajo')),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='mantenimiento.partetrabajo')),
            ],
        ),
    ]
