# Generated by Django 3.1.7 on 2025-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0062_gastosparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastosparte',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
