# Generated by Django 3.1.7 on 2025-10-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0063_gastosparte_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastosparte',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='mantenimiento.lineapartetrabajo'),
        ),
    ]
