# Generated by Django 3.1.7 on 2025-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0064_auto_20251030_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='que',
            field=models.TextField(max_length=750),
        ),
    ]
