# Generated by Django 3.1.7 on 2026-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0065_auto_20251120_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='partetrabajo',
            name='fecha_estimada_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
