# Generated by Django 3.1.7 on 2025-05-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flejes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('idProduccion', models.CharField(max_length=10)),
                ('IdArticulo', models.CharField(max_length=12)),
                ('peso', models.IntegerField()),
                ('of', models.CharField(max_length=8)),
                ('maquina_siglas', models.CharField(max_length=4)),
                ('descripcion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Acumulador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estructura.zona')),
            ],
        ),
    ]
