# Generated by Django 3.1.7 on 2025-05-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulador',
            name='bobina_activa',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='flejes',
            name='acumulador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flejes', to='trazabilidad.acumulador'),
        ),
    ]
