# Generated by Django 3.1.7 on 2025-05-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0002_auto_20250515_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flejes',
            name='acumulador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flejes', to='trazabilidad.acumulador'),
        ),
    ]
