# Generated by Django 3.1.7 on 2025-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0003_auto_20250515_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulador',
            name='maquina_siglas',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
