# Generated by Django 3.1.7 on 2025-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0005_acumulador_bobina_ultima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acumulador',
            name='bobina_activa',
        ),
        migrations.RemoveField(
            model_name='acumulador',
            name='bobina_ultima',
        ),
        migrations.AddField(
            model_name='acumulador',
            name='n_bobina_activa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acumulador',
            name='n_bobina_ultima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acumulador',
            name='of_activa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
