# Generated by Django 3.1.7 on 2025-05-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0006_auto_20250519_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flejes',
            name='activo',
        ),
    ]
