# Generated by Django 3.1.7 on 2025-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0007_remove_flejes_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flejes',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flejes',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flejes',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flejes',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flejes',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flejes',
            name='metros_medido',
            field=models.FloatField(default=0),
        ),
    ]
