# Generated by Django 3.1.7 on 2025-06-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0009_auto_20250526_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tubos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_tubos', models.IntegerField(default=0)),
                ('largo', models.FloatField()),
                ('fleje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tubos', to='trazabilidad.flejes')),
            ],
        ),
    ]
