# Generated by Django 3.1.7 on 2026-01-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0010_tubos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubos',
            name='dim1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubos',
            name='dim2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
