# Generated by Django 3.1.7 on 2026-01-16 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0011_auto_20260116_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='OF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='flejes',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flejes', to='trazabilidad.of'),
        ),
    ]
