# Generated by Django 3.1.7 on 2026-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0012_auto_20260116_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
