# Generated by Django 3.1.7 on 2026-01-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estructura', '0013_auto_20241203_0710'),
        ('trazabilidad', '0013_auto_20260116_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='of',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estructura.zona'),
        ),
    ]
