# Generated by Django 3.1.7 on 2026-02-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0014_of_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='tubos',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubos',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubos',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tubos',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
