# Generated by Django 3.1.7 on 2026-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0015_auto_20260202_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tubos',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='tubos',
            name='hora_salida',
        ),
        migrations.AlterField(
            model_name='tubos',
            name='fecha_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tubos',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
