# Generated by Django 3.1.7 on 2026-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0016_auto_20260202_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='of',
            name='grupo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
