# Generated by Django 3.1.7 on 2026-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0017_of_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='of',
            name='grupo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
