# Generated by Django 3.1.7 on 2026-02-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0019_auto_20260216_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('codigo_forma', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
                ('abreviatura', models.CharField(max_length=8)),
            ],
        ),
    ]
