# Generated by Django 3.1.7 on 2026-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0020_forma'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumulador',
            name='maquila_siglas',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
