# Generated by Django 3.1.7 on 2026-03-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trazabilidad', '0021_acumulador_maquila_siglas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xIdMontaje', models.CharField(max_length=7)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montajes', to='trazabilidad.of')),
            ],
        ),
        migrations.AddField(
            model_name='tubos',
            name='montaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tubos', to='trazabilidad.montaje'),
        ),
    ]
